//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.IO;
using VarDump.CodeDom.Common;
using VarDump.CodeDom.Compiler;

namespace VarDump.Extensions;
using System.Threading.Tasks;

internal static partial class CodeGeneratorExtensions
{
    public static async Task GenerateCodeAsync(this ICodeGenerator codeGenerator, CodeObject co, TextWriter w,
        CodeGeneratorOptions o)
    {
        switch (co)
        {
            case CodeExpression ce:
                await (codeGenerator.GenerateCodeFromExpressionAsync(ce, w, o)).ConfigureAwait(false);
                break;
            case CodeStatement cs:
                await (codeGenerator.GenerateCodeFromStatementAsync(cs, w, o)).ConfigureAwait(false);
                break;
            default:
                throw new InvalidOperationException("CodeExpression and CodeStatement supported only.");
        }
    }
}