//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.CodeDom.Compiler;
using System.IO;

namespace VarDump.CodeDom.Compiler
{
    using System.Threading.Tasks;
    internal sealed partial class ExposedTabStringIndentedTextWriter : IndentedTextWriter
    {

        internal async Task InternalOutputTabsAsync()
        {
            TextWriter inner = InnerWriter;
            for (int i = 0; i < Indent; i++)
            {
                await (inner.WriteAsync(TabString)).ConfigureAwait(false);
            }
        }
    }
}
