//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.IO;
using VarDump.CodeDom.Common;

namespace VarDump.CodeDom.Compiler
{
    using System.Threading.Tasks;
    internal partial interface ICodeGenerator
    {
        Task GenerateCodeFromExpressionAsync(CodeExpression e, TextWriter w, CodeGeneratorOptions o);
        Task GenerateCodeFromStatementAsync(CodeStatement e, TextWriter w, CodeGeneratorOptions o);
    }
}
