//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.IO;
using System.Threading.Tasks;
using VarDump.CodeDom.Common;
using VarDump.CodeDom.Compiler;
using VarDump.CodeDom.CSharp;
using VarDump.Extensions;
using VarDump.Utils;
using VarDump.Visitor;

namespace VarDump;

public partial class CSharpDumper : IDumper
{

    public async Task DumpAsync(object obj, TextWriter textWriter)
    {
        if (textWriter == null)
        {
            throw new ArgumentNullException(nameof(textWriter));
        }

        var objectVisitor = new ObjectVisitor(_options);

        var expression = objectVisitor.Visit(obj);

        CodeObject codeObject = _options.GenerateVariableInitializer
            ? new CodeVariableDeclarationStatement(new CodeImplicitlyTypedTypeReference(),
                obj != null ? ReflectionUtils.ComposeCsharpVariableName(obj.GetType()) : "nullValue")
            {
                InitExpression = expression
            }
            : expression;

        var codeGeneratorOptions = new CodeGeneratorOptions
        {
            BracingStyle = "C"
        };

        ICodeGenerator generator = new CSharpCodeGenerator();

        await generator.GenerateCodeAsync(codeObject, textWriter, codeGeneratorOptions);
    }
}