//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.IO;

namespace VarDump;
using System.Threading.Tasks;

public partial interface IDumper
{
    Task DumpAsync(object obj, TextWriter textWriter);
}