//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.IO;
using VarDump.Async;
using VarDump.CodeDom.Common;
using VarDump.CodeDom.Compiler;
using VarDump.CodeDom.VisualBasic;
using VarDump.Extensions;
using VarDump.Utils;
using VarDump.Visitor;

namespace VarDump;
using System.Threading.Tasks;

public partial class VisualBasicDumper : IDumper
{

    public async Task DumpAsync(object obj, TextWriter textWriter)
    {
        if(textWriter == null)
        {
            throw new ArgumentNullException(nameof(textWriter));
        }

        var objectVisitor = new ObjectVisitor(_options);

        var expression = objectVisitor.Visit(obj);

        CodeObject codeObject = _options.GenerateVariableInitializer
            ? new CodeVariableDeclarationStatement(new CodeImplicitlyTypedTypeReference(),
                obj != null ? ReflectionUtils.ComposeVisualBasicVariableName(obj.GetType()) : "nullValue")
            {
                InitExpression = expression
            }
            : expression;

        ICodeGenerator generator = new VBCodeGenerator();

        await generator.GenerateCodeAsync(codeObject, textWriter, new CodeGeneratorOptions());
    }
}